Add support for hyper-openssl + Tokio 1.0 upgrade
Azure/hyper-proxy pull request #2
Opened 2021-02-18 21:51 UTC by massand

2021-02-18 22:30 UTC, arsing requested changes

2021-02-18 22:30 UTC, arsing commented on Changelog.md
> -> Legend:
Restore this file. No reason to delete it.

2021-02-18 22:30 UTC, arsing commented on LICENSE-MIT.md
> -The MIT License (MIT)
Currently you've deleted the original author's copyright and substituted your own.

Restore this file, then remove `2017` from line 3 and add `, Microsoft Corporation` at the end.

2021-02-18 22:30 UTC, arsing commented on README.md
> +- The original Hyper proxy crate does not support openssl engines via `hyper-openssl`. This is a feature requirement within the Azure IoT Identity Service binaries, in order to establish TLS handshak
Probably good to add one more paragraph here like:

```
We aim to upstream these changes to the tafia/hyper-proxy repository when it gains tokio 1.0.
```

2021-02-18 22:30 UTC, arsing commented on Cargo.toml
> +typed-headers = "0.2"
The tokio-1.0 PR reverted to `headers` with https://github.com/tafia/hyper-proxy/pull/18/commits/4be706f2f0297bd3d14f301b6ea0be8f3078bb17

2021-02-18 22:30 UTC, arsing commented on src/lib.rs
> +/// A Proxy Stream wrapper
Move all this back to `stream.rs`

2021-02-18 22:34 UTC, daprilik reviewed
One broad question: is there any specific reason you decided to remove `mod stream` and push everything into `lib.rs`?

EDIT: looks like Arnav beat me to the punch https://github.com/Azure/hyper-proxy/pull/2#discussion_r578792085

2021-02-18 22:34 UTC, daprilik commented on src/lib.rs
> +                                    .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;
Use `map_err(io_err)` to be consistent.

(sidenote: I would be in favor of applying this `io_err` helper function in our codebase as well, since we have lots of similar `map_err`s strewn about)

2021-02-18 23:08 UTC, massand commented on Cargo.toml
> +typed-headers = "0.2"
I cannot recollect the reason I reverted this now. So, I will restore the headers crate usage here.

2021-02-18 23:10 UTC, massand commented on src/lib.rs
> +                                    .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;
Fixed

2021-02-18 23:10 UTC, massand commented on src/lib.rs
> +/// A Proxy Stream wrapper
Fixed

2021-02-18 23:10 UTC, massand commented on README.md
> +- The original Hyper proxy crate does not support openssl engines via `hyper-openssl`. This is a feature requirement within the Azure IoT Identity Service binaries, in order to establish TLS handshak
Fixed

2021-02-18 23:10 UTC, massand commented on LICENSE-MIT.md
> -The MIT License (MIT)
Fixed

2021-02-18 23:10 UTC, massand commented on Changelog.md
> -> Legend:
Fixed

2021-02-18 23:32 UTC, arsing requested changes

2021-02-18 23:32 UTC, arsing commented on src/stream.rs
>      }
Also add `write_vectored` and `is_write_vectored`. No reason to disable it even when the underlying stream supports it.

2021-02-18 23:32 UTC, arsing commented on src/stream.rs
> +}
Restore newline at end of file.

2021-02-18 23:35 UTC, arsing commented on Cargo.toml
>  rustls = ["rustls-base", "rustls-native-certs"]
This should be:

```rust
rustls = ["rustls-base", "rustls-native-certs", "hyper-rustls/native-tokio"]
rustls-webpki = ["rustls-base", "webpki-roots", "hyper-rustls/webpki-tokio"]
```

based on upstream.

2021-02-18 23:36 UTC, arsing commented on Cargo.toml
> +default = ["openssl-tls"]
Just keep `tls` as the default. We can override it ourselves. We'll have to do that in the future anyway once we start using upstream instead of the fork.

2021-02-18 23:40 UTC, arsing commented
(For reference, the correct diff is https://github.com/Azure/hyper-proxy/compare/master..pull/2/head , not what GH thinks it is.)

2021-02-18 23:54 UTC, massand commented on src/stream.rs
> +}
Oops. Fixed.

2021-02-18 23:54 UTC, massand commented on src/stream.rs
>      }
Fixed.

2021-02-18 23:57 UTC, massand commented on Cargo.toml
> +default = ["openssl-tls"]
Sure. I'll add the feature in my PR - https://github.com/Azure/iot-identity-service/pull/114

2021-02-18 23:57 UTC, massand commented on src/stream.rs
>      }
Fixed.

2021-02-18 23:58 UTC, massand commented on src/stream.rs
> +}
Oops. Fixed.

2021-02-19 00:04 UTC, arsing approved these changes

2021-02-19 00:04 UTC, massand commented on Cargo.toml
>  rustls = ["rustls-base", "rustls-native-certs"]
Fixed. Somehow this got yanked in commit 76c30325

2021-02-19 00:21 UTC, arsing commented on Cargo.toml
>  rustls = ["rustls-base", "rustls-native-certs"]
Because it was part of the two commits in master that were not part of your original branch, so overwriting latest master with your copy effectively reverted them.

2021-02-19 00:27 UTC, massand commented
Thanks @arsing! 
As discussed, I am merging the two commits separately into master. Closing this approved PR.

2021-02-19 00:27 UTC, closed without merging